import { Platform, StyleSheet } from "react-native";

import {
  StitchColors,
  StitchFonts,
  StitchRadius,
} from "@/src/theme/wordlyStitchTheme";

export const revisionScreenStyles = StyleSheet.create({
  listScreen: {
    flex: 1,
    backgroundColor: StitchColors.surface,
  },
  listFlat: {
    flex: 1,
  },
  listContent: {
    paddingHorizontal: 24,
    paddingBottom: 32,
    flexGrow: 1,
  },
  listHeaderBlock: {
    paddingTop: 4,
    paddingBottom: 8,
  },
  libraryStats: {
    fontSize: 15,
    fontFamily: StitchFonts.bodyMedium,
    color: StitchColors.onSurfaceVariant,
  },
  heroCta: {
    marginTop: 24,
    marginBottom: 12,
    borderRadius: StitchRadius.lg,
    backgroundColor: StitchColors.primary,
    paddingVertical: 28,
    paddingHorizontal: 24,
    overflow: "hidden",
    shadowColor: StitchColors.primary,
    shadowOpacity: 0.22,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 12 },
    elevation: 6,
  },
  heroCtaInner: {
    zIndex: 1,
  },
  heroCtaBadgeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 14,
  },
  heroCtaIconWrap: {
    backgroundColor: "rgba(255,255,255,0.2)",
    borderRadius: StitchRadius.sm,
    padding: 8,
  },
  heroCtaKicker: {
    color: "rgba(250,248,255,0.85)",
    fontFamily: StitchFonts.bodySemi,
    fontSize: 11,
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  heroCtaTitle: {
    color: StitchColors.onPrimary,
    fontFamily: StitchFonts.headline,
    fontSize: 22,
    marginBottom: 4,
  },
  heroCtaSubtitle: {
    color: "rgba(250,248,255,0.72)",
    fontFamily: StitchFonts.body,
    fontSize: 14,
  },
  heroCtaDecor: {
    position: "absolute",
    right: -32,
    bottom: -32,
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: "rgba(255,255,255,0.1)",
  },
  /** Pasek: szybkie wyszukiwanie + przycisk otwierający wyspę filtrów (Stitch). */
  filtersTriggerRow: {
    marginTop: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  filtersSearchFieldCompact: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: StitchColors.surfaceContainerLow,
    borderRadius: StitchRadius.lg,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  filtersSearchInputCompact: {
    flex: 1,
    marginLeft: 8,
    fontSize: 16,
    fontFamily: StitchFonts.body,
    color: StitchColors.onSurface,
    paddingVertical: 2,
    minHeight: 24,
  },
  filtersOpenBtn: {
    position: "relative",
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: StitchColors.surfaceContainerLow,
    alignItems: "center",
    justifyContent: "center",
  },
  filterBadge: {
    position: "absolute",
    top: 2,
    right: 2,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: StitchColors.primary,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 5,
  },
  filterBadgeText: {
    fontSize: 10,
    fontFamily: StitchFonts.bodySemi,
    color: StitchColors.onPrimary,
  },
  levelFilterChip: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: StitchRadius.full,
    borderWidth: 1,
    minHeight: 40,
    justifyContent: "center",
  },
  levelFilterChipOff: {
    backgroundColor: StitchColors.surfaceContainerLow,
    borderColor: "rgba(175,179,179,0.5)",
  },
  levelFilterChipOn: {
    backgroundColor: StitchColors.primary,
    borderColor: StitchColors.primaryDim,
  },
  levelFilterChipText: {
    fontSize: 13,
    fontFamily: StitchFonts.bodySemi,
    letterSpacing: 0.2,
  },
  levelFilterChipTextOff: {
    color: StitchColors.onSurfaceVariant,
  },
  levelFilterChipTextOn: {
    color: StitchColors.onPrimary,
  },
  sectionRecentLabel: {
    marginTop: 22,
    marginBottom: 14,
    fontSize: 12,
    fontFamily: StitchFonts.bodySemi,
    color: StitchColors.onSurfaceVariant,
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  sectionTitle: {
    fontSize: 22,
    fontFamily: StitchFonts.headline,
    color: StitchColors.onSurface,
  },
  sectionHint: {
    fontSize: 13,
    fontFamily: StitchFonts.body,
    color: StitchColors.onSurfaceVariant,
    marginTop: 4,
  },
  headerCta: {
    marginTop: 16,
    backgroundColor: StitchColors.primary,
    borderRadius: StitchRadius.lg,
    paddingVertical: 16,
    alignItems: "center",
  },
  headerCtaText: {
    color: StitchColors.onPrimary,
    fontFamily: StitchFonts.bodySemi,
    fontSize: 16,
  },
  headerCtaHint: {
    color: StitchColors.surfaceContainerHighest,
    fontFamily: StitchFonts.body,
    fontSize: 12,
    marginTop: 4,
  },
  emptyList: {
    paddingVertical: 32,
    alignItems: "center",
  },
  rowCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    justifyContent: "space-between",
    backgroundColor: StitchColors.surfaceContainerLowest,
    borderRadius: StitchRadius.md,
    paddingVertical: 18,
    paddingHorizontal: 16,
    marginBottom: 14,
    shadowColor: StitchColors.onSurface,
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  rowLevelCol: {
    width: 44,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  rowCefrPill: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: StitchRadius.full,
    alignItems: "center",
    justifyContent: "center",
  },
  rowMain: {
    flex: 1,
    minWidth: 0,
    marginRight: 4,
  },
  rowWord: {
    fontSize: 17,
    fontFamily: StitchFonts.headline,
    color: StitchColors.onSurface,
  },
  rowCefrPillText: {
    fontSize: 10,
    fontFamily: StitchFonts.bodySemi,
    letterSpacing: 0.3,
    textTransform: "uppercase",
  },
  rowChevron: {
    marginLeft: 8,
  },
  searchEmpty: {
    paddingVertical: 24,
    alignItems: "center",
  },
  searchEmptyText: {
    fontSize: 15,
    fontFamily: StitchFonts.body,
    color: StitchColors.onSurfaceVariant,
    textAlign: "center",
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(47,51,52,0.4)",
    justifyContent: "flex-end",
  },
  modalCard: {
    backgroundColor: StitchColors.surfaceContainerLowest,
    borderTopLeftRadius: StitchRadius.lg,
    borderTopRightRadius: StitchRadius.lg,
    maxHeight: "88%",
    paddingTop: 8,
  },
  modalScroll: {
    paddingHorizontal: 20,
    paddingBottom: 12,
  },
  modalTitle: {
    fontSize: 28,
    fontFamily: StitchFonts.headline,
    color: StitchColors.onSurface,
    marginTop: 8,
  },
  modalTarget: {
    fontSize: 20,
    fontFamily: StitchFonts.bodyMedium,
    color: StitchColors.onSurfaceVariant,
    marginTop: 6,
  },
  modalSection: {
    marginTop: 20,
    fontSize: 12,
    fontFamily: StitchFonts.bodySemi,
    color: StitchColors.onSurfaceVariant,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  modalMeta: {
    marginTop: 16,
    fontSize: 13,
    fontFamily: StitchFonts.body,
    color: StitchColors.onSurfaceVariant,
  },
  modalActions: {
    flexDirection: "row",
    gap: 10,
    paddingHorizontal: 20,
    paddingBottom: 24,
    paddingTop: 8,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: StitchColors.surfaceContainer,
  },
  screen: {
    flex: 1,
    padding: 20,
    gap: 12,
    backgroundColor: StitchColors.surface,
  },
  /** Powtórka (fiszki): safe area u góry w `RevisionFlashcardMode` (`revisionFlashHeaderInset`). */
  revisionFlashcardScreen: {
    flex: 1,
    paddingHorizontal: 0,
    paddingTop: 0,
    paddingBottom: 10,
    gap: 14,
    backgroundColor: StitchColors.surface,
  },
  /**
   * Wyjdź, Powtórka / Postęp, pasek: inset + wyższy z-index/elevation niż karta,
   * żeby karta (elevation) nie rysowała się nad tą sekcją na Androidzie.
   */
  revisionFlashHeaderInset: {
    width: "100%",
    paddingHorizontal: 20,
    maxWidth: 640,
    alignSelf: "center",
    zIndex: 10,
    ...(Platform.OS === "android" ? { elevation: 12 } : {}),
  },
  /** Ciaśniejszy padding wewnątrz karty słowa w powtórce (nadpisuje homeWordCardStyles.focalInner). */
  revisionWordCardInner: {
    paddingHorizontal: 16,
    paddingVertical: 26,
  },
  flashSessionHeader: {
    width: "100%",
    maxWidth: 640,
    alignSelf: "center",
    marginBottom: 12,
    gap: 14,
  },
  /** Etykieta „Powtórka” lekko nad wierszem Postęp + licznik (subheader). */
  flashSessionHeadingBlock: {
    width: "100%",
    gap: 6,
  },
  /** Wiersz: Postęp po lewej, „1 z N” po prawej (space-between). */
  flashSessionTitleRow: {
    width: "100%",
  },
  flashSessionTitleWithCount: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    flexWrap: "wrap",
  },
  flashSessionLabel: {
    fontSize: 11,
    fontFamily: StitchFonts.label,
    color: StitchColors.onSurfaceVariant,
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  flashSessionTitle: {
    fontSize: 22,
    fontFamily: StitchFonts.headline,
    color: StitchColors.onSurface,
  },
  flashSessionCountCurrent: {
    fontSize: 20,
    fontFamily: StitchFonts.headline,
    color: StitchColors.primary,
  },
  flashSessionCountRest: {
    fontSize: 14,
    fontFamily: StitchFonts.headline,
    color: StitchColors.onSurfaceVariant,
  },
  progressTrack: {
    height: 8,
    borderRadius: StitchRadius.full,
    backgroundColor: StitchColors.surfaceContainerHighest,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: StitchRadius.full,
    backgroundColor: StitchColors.secondary,
  },
  captionCenter: {
    color: StitchColors.onSurfaceVariant,
    fontSize: 13,
    fontFamily: StitchFonts.bodySemi,
  },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
    gap: 10,
    backgroundColor: StitchColors.surface,
  },
  flashCardOuter: {
    flex: 1,
    minHeight: 120,
    width: "100%",
    zIndex: 0,
    ...(Platform.OS === "android" ? { elevation: 0 } : {}),
  },
  revisionRevealScroll: {
    flex: 1,
    width: "100%",
    zIndex: 0,
    ...(Platform.OS === "android" ? { elevation: 0 } : {}),
  },
  revisionRevealScrollContent: {
    flexGrow: 1,
    paddingBottom: 12,
    /** Minimalny odstęp karty od krawędzi ekranu (górny pasek ma większy inset). */
    paddingHorizontal: 10,
    paddingTop: 8,
    justifyContent: "flex-start",
  },
  card: {
    flex: 1,
    borderRadius: StitchRadius.md,
    paddingHorizontal: 28,
    paddingVertical: 36,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: StitchColors.surfaceContainerLowest,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderLeftWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(175,179,179,0.12)",
    shadowColor: StitchColors.onSurface,
    shadowOpacity: 0.06,
    shadowRadius: 40,
    shadowOffset: { width: 0, height: 24 },
    elevation: 4,
  },
  /** Jedna karta: hasło → przycisk reveal → blok tłumaczenia (bez „obracania”). */
  revisionRevealCard: {
    width: "100%",
    maxWidth: 400,
    alignSelf: "center",
    justifyContent: "flex-start",
    alignItems: "stretch",
    minHeight: 280,
  },
  revisionRevealAudio: {
    marginTop: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    alignSelf: "center",
    paddingHorizontal: 18,
  },
  revealTranslationPrimary: {
    marginTop: 24,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    paddingVertical: 16,
    paddingHorizontal: 22,
    borderRadius: StitchRadius.lg,
    backgroundColor: StitchColors.primary,
    alignSelf: "stretch",
    shadowColor: StitchColors.primary,
    shadowOpacity: 0.2,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  revealTranslationPrimaryText: {
    fontSize: 16,
    fontFamily: StitchFonts.headline,
    color: StitchColors.onPrimary,
  },
  revisionRevealTranslationBlock: {
    marginTop: 24,
    width: "100%",
    alignItems: "stretch",
    gap: 8,
  },
  revisionRevealTranslationHeading: {
    textAlign: "center",
    width: "100%",
  },
  revisionRevealExample: {
    marginTop: 16,
    padding: 14,
    borderRadius: StitchRadius.md,
    backgroundColor: StitchColors.surfaceContainerLow,
    gap: 8,
  },
  revisionRevealExampleLabel: {
    fontSize: 10,
    fontFamily: StitchFonts.bodySemi,
    letterSpacing: 1.5,
    textTransform: "uppercase",
    color: StitchColors.outlineVariant,
    textAlign: "center",
  },
  revealHideLink: {
    marginTop: 18,
    alignSelf: "center",
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  revealHideLinkText: {
    fontSize: 15,
    fontFamily: StitchFonts.bodySemi,
    color: StitchColors.primary,
  },
  cardLemma: {
    fontSize: 40,
    fontFamily: StitchFonts.display,
    color: StitchColors.onSurface,
    textAlign: "center",
    letterSpacing: -0.5,
  },
  cardIpa: {
    marginTop: 10,
    marginBottom: 20,
    fontSize: 17,
    fontFamily: StitchFonts.body,
    fontStyle: "italic",
    color: StitchColors.onSurfaceVariant,
    textAlign: "center",
  },
  flipButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 14,
    paddingHorizontal: 26,
    borderRadius: StitchRadius.lg,
    backgroundColor: "rgba(68, 86, 186, 0.1)",
  },
  flipButtonText: {
    fontSize: 16,
    fontFamily: StitchFonts.headline,
    color: StitchColors.primary,
  },
  cardBackBody: {
    fontSize: 20,
    fontFamily: StitchFonts.bodyMedium,
    color: StitchColors.onSurface,
    textAlign: "center",
    lineHeight: 28,
  },
  cardBackTranslationSep: {
    fontSize: 20,
    lineHeight: 28,
    fontFamily: StitchFonts.bodyMedium,
    color: StitchColors.outlineVariant,
  },
  title: {
    fontSize: 22,
    fontFamily: StitchFonts.headline,
    color: StitchColors.onSurface,
  },
  subtitle: {
    fontSize: 15,
    fontFamily: StitchFonts.body,
    textAlign: "center",
    color: StitchColors.onSurfaceVariant,
  },
  label: {
    color: StitchColors.onSurfaceVariant,
    fontFamily: StitchFonts.label,
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  word: {
    fontSize: 30,
    fontFamily: StitchFonts.headline,
    color: StitchColors.onSurface,
  },
  hint: {
    color: StitchColors.onSurfaceVariant,
    fontFamily: StitchFonts.body,
    marginTop: 8,
  },
  audioButton: {
    borderRadius: StitchRadius.sm,
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: StitchColors.surfaceContainer,
    marginTop: 4,
  },
  audioButtonText: {
    color: StitchColors.onSurface,
    fontFamily: StitchFonts.bodySemi,
  },
  example: {
    marginTop: 4,
    color: StitchColors.onSurface,
    fontFamily: StitchFonts.body,
    fontSize: 14,
  },
  exampleMuted: {
    color: StitchColors.onSurfaceVariant,
    fontFamily: StitchFonts.body,
    fontSize: 14,
  },
  flashNavRow: {
    marginTop: "auto",
    paddingTop: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    width: "100%",
    maxWidth: 440,
    alignSelf: "center",
    paddingHorizontal: 20,
    /** paddingBottom domyślnie; iPhone: nadpisane przez safe area w komponencie */
    paddingBottom: 8,
  },
  /**
   * Zamknięcie powtórki po lewej od „Wstecz”.
   * Delikatny ton „error” (nie pełny alert), żeby było widać, że to wyjście z sesji.
   */
  flashNavClose: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    backgroundColor: "rgba(168, 54, 75, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(168, 54, 75, 0.38)",
  },
  actions: {
    marginTop: "auto",
    flexDirection: "row",
    gap: 10,
  },
  flashNavButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 14,
    borderRadius: StitchRadius.lg,
  },
  flashNavPrev: {
    backgroundColor: StitchColors.surfaceContainerLow,
  },
  flashNavPrevDisabled: {
    opacity: 0.45,
  },
  flashNavNext: {
    backgroundColor: StitchColors.primary,
    shadowColor: StitchColors.primary,
    shadowOpacity: 0.25,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  flashNavPrevText: {
    fontSize: 15,
    fontFamily: StitchFonts.headline,
    color: StitchColors.onSurfaceVariant,
  },
  flashNavNextText: {
    fontSize: 15,
    fontFamily: StitchFonts.headline,
    color: StitchColors.onPrimary,
  },
  primaryButton: {
    flex: 1,
    backgroundColor: StitchColors.primary,
    borderRadius: StitchRadius.md,
    paddingVertical: 12,
    alignItems: "center",
  },
  primaryButtonText: {
    color: StitchColors.onPrimary,
    fontFamily: StitchFonts.bodySemi,
  },
  secondaryButton: {
    flex: 1,
    backgroundColor: StitchColors.surfaceContainerHigh,
    borderRadius: StitchRadius.md,
    paddingVertical: 12,
    alignItems: "center",
  },
  secondaryButtonText: {
    color: StitchColors.onSurface,
    fontFamily: StitchFonts.bodySemi,
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  hubScroll: {
    flex: 1,
    backgroundColor: StitchColors.surface,
  },
  hubScrollContent: {
    paddingHorizontal: 24,
    paddingBottom: 40,
  },
  hubIntro: {
    marginBottom: 22,
  },
  hubTitle: {
    fontSize: 32,
    lineHeight: 38,
    fontFamily: StitchFonts.display,
    color: StitchColors.onSurface,
    letterSpacing: -0.6,
    marginBottom: 8,
  },
  hubTagline: {
    fontSize: 16,
    lineHeight: 24,
    fontFamily: StitchFonts.body,
    color: StitchColors.onSurfaceVariant,
    maxWidth: 400,
  },
  hubHeroCard: {
    borderRadius: StitchRadius.lg,
    backgroundColor: StitchColors.surfaceContainerLow,
    padding: 24,
    marginBottom: 16,
    overflow: "hidden",
  },
  hubHeroDecor: {
    position: "absolute",
    right: 12,
    top: 16,
    opacity: 0.12,
  },
  hubHeroKicker: {
    fontSize: 11,
    fontFamily: StitchFonts.bodySemi,
    letterSpacing: 2,
    textTransform: "uppercase",
    color: StitchColors.primary,
    marginBottom: 8,
  },
  hubHeroTitle: {
    fontSize: 22,
    fontFamily: StitchFonts.headline,
    color: StitchColors.onSurface,
    marginBottom: 6,
  },
  hubHeroDesc: {
    fontSize: 14,
    fontFamily: StitchFonts.body,
    color: StitchColors.onSurfaceVariant,
    marginBottom: 16,
    maxWidth: "92%",
  },
  hubHeroMeta: {
    fontSize: 13,
    fontFamily: StitchFonts.bodyMedium,
    color: StitchColors.onSurfaceVariant,
  },
  hubRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 12,
  },
  hubRowItem: {
    flex: 1,
    minWidth: 0,
  },
  hubCard: {
    borderRadius: StitchRadius.lg,
    backgroundColor: StitchColors.surfaceContainerLow,
    padding: 18,
    minHeight: 132,
    justifyContent: "space-between",
  },
  hubCardTitle: {
    fontSize: 17,
    fontFamily: StitchFonts.headline,
    color: StitchColors.onSurface,
    marginBottom: 6,
  },
  hubCardDesc: {
    fontSize: 13,
    fontFamily: StitchFonts.body,
    color: StitchColors.onSurfaceVariant,
    lineHeight: 19,
  },
  hubSoonBadge: {
    alignSelf: "flex-start",
    marginTop: 10,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: StitchRadius.sm,
    backgroundColor: StitchColors.surfaceContainerHighest,
  },
  hubSoonBadgeText: {
    fontSize: 11,
    fontFamily: StitchFonts.bodySemi,
    color: StitchColors.onSurfaceVariant,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  /** Quick Practice (5 / 10 / 20): jeden rząd, pełna szerokość, równe segmenty. */
  hubQuickRow: {
    width: "100%",
    alignSelf: "stretch",
    flexDirection: "row",
    alignItems: "stretch",
    gap: 10,
  },
  hubQuickChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: StitchRadius.md,
    backgroundColor: StitchColors.primary,
  },
  hubQuickChipText: {
    fontSize: 14,
    fontFamily: StitchFonts.bodySemi,
    color: StitchColors.onPrimary,
  },
  hubLevelHint: {
    marginTop: 10,
    fontSize: 12,
    fontFamily: StitchFonts.bodyMedium,
    color: StitchColors.primary,
  },
  /** Stitch: bento, jedna kolumna, pełna szerokość. */
  hubBentoWrap: {
    gap: 16,
    width: "100%",
    alignItems: "stretch",
  },
  hubTileFull: {
    width: "100%",
    alignSelf: "stretch",
  },
  /** Główny tryb: biała karta jak reszta, wyższa akcentem (obramowanie + cień primary). */
  hubDailyFeatured: {
    borderWidth: 2,
    borderColor: `${StitchColors.primary}4D`,
    shadowColor: StitchColors.primary,
    shadowOpacity: 0.14,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 5 },
    elevation: 4,
    overflow: "hidden",
    position: "relative",
    /** Nadpisuje minHeight z `hubCardWhite` (220): treść jest niska, ikona jest absolute. */
    minHeight: 0,
    alignItems: "stretch",
  },
  /** Tytuł + opis: miejsce pod ikonę z prawej (absolute). */
  hubDailyTextBlock: {
    position: "relative",
    zIndex: 1,
    paddingRight: 100,
    marginBottom: 4,
  },
  /** „Words ready” + strzałka na pełną szerokość karty (poza wąskim blokiem tekstu). */
  hubDailyMetaRow: {
    marginTop: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    alignSelf: "stretch",
    zIndex: 1,
  },
  /** Jak `hubCardDescSm`, bez flexGrow (inaczej rozpycha pionowo kartę z minHeight). */
  hubDailyDesc: {
    fontSize: 13,
    fontFamily: StitchFonts.body,
    color: StitchColors.onSurfaceVariant,
    lineHeight: 20,
  },
  /** Duża ikona psychology z prawej, częściowo jak tło karty (jak wcześniejszy hero). */
  hubDailyIconDecor: {
    position: "absolute",
    right: -6,
    top: 4,
    opacity: 0.2,
  },
  hubDailyCardTitle: {
    fontSize: 22,
    fontFamily: StitchFonts.headline,
    color: StitchColors.onSurface,
    marginBottom: 8,
  },
  hubStartSessionBtn: {
    backgroundColor: StitchColors.primary,
    paddingHorizontal: 28,
    paddingVertical: 14,
    borderRadius: StitchRadius.md,
    shadowColor: StitchColors.primary,
    shadowOpacity: 0.28,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  hubStartSessionBtnText: {
    fontSize: 15,
    fontFamily: StitchFonts.bodySemi,
    color: StitchColors.onPrimary,
  },
  hubSessionSheetBody: {
    paddingTop: 8,
    gap: 20,
  },
  hubSessionIntro: {
    fontSize: 16,
    fontFamily: StitchFonts.body,
    color: StitchColors.onSurfaceVariant,
    lineHeight: 24,
  },
  hubSessionSheetPrimary: {
    marginTop: 8,
    alignSelf: "stretch",
    alignItems: "center",
  },
  hubCardWhite: {
    borderRadius: StitchRadius.lg,
    backgroundColor: "#FFFFFF",
    padding: 22,
    borderWidth: 1,
    borderColor: `${StitchColors.outlineVariant}22`,
    minHeight: 220,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  hubIconCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 18,
  },
  hubCardTitleSm: {
    fontSize: 20,
    fontFamily: StitchFonts.headline,
    color: StitchColors.onSurface,
    marginBottom: 8,
  },
  hubCardDescSm: {
    fontSize: 13,
    fontFamily: StitchFonts.body,
    color: StitchColors.onSurfaceVariant,
    lineHeight: 20,
    flexGrow: 1,
  },
  hubQuickSegment: {
    flex: 1,
    minWidth: 0,
    borderRadius: StitchRadius.md,
    borderWidth: 2,
    borderColor: `${StitchColors.outlineVariant}55`,
    backgroundColor: StitchColors.surfaceContainerLow,
    paddingVertical: 14,
    paddingHorizontal: 6,
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
  },
  hubQuickSegmentSelected: {
    borderColor: StitchColors.primary,
    backgroundColor: `${StitchColors.primary}14`,
  },
  hubQuickSegmentValue: {
    fontSize: 20,
    fontFamily: StitchFonts.headline,
    color: StitchColors.onSurface,
  },
  hubQuickSegmentValueSelected: {
    color: StitchColors.primary,
  },
  hubQuickSegmentUnit: {
    fontSize: 11,
    fontFamily: StitchFonts.bodyMedium,
    color: StitchColors.onSurfaceVariant,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  hubQuickSegmentUnitSelected: {
    color: StitchColors.primary,
  },
  hubSmallMetaRow: {
    marginTop: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  /** Gdy brak lewej etykiety (np. Level Practice bez słów): strzałka w prawo. */
  hubSmallMetaRowEnd: {
    justifyContent: "flex-end",
  },
  hubLevelGrid: {
    width: "100%",
    gap: 12,
  },
  hubLevelGridRow: {
    flexDirection: "row",
    gap: 12,
    width: "100%",
  },
  hubLevelGridCell: {
    flex: 1,
    minWidth: 0,
    borderRadius: StitchRadius.lg,
    backgroundColor: StitchColors.surfaceContainerLow,
    paddingVertical: 16,
    paddingHorizontal: 14,
    minHeight: 96,
    borderWidth: 1,
    borderColor: `${StitchColors.outlineVariant}80`,
    justifyContent: "center",
  },
  hubLevelGridCellDisabled: {
    opacity: 0.55,
    backgroundColor: StitchColors.surfaceContainerHighest,
  },
  hubLevelGridCellTitle: {
    fontSize: 20,
    fontFamily: StitchFonts.headline,
    color: StitchColors.onSurface,
    marginBottom: 6,
  },
  hubLevelGridCellMeta: {
    fontSize: 13,
    fontFamily: StitchFonts.bodyMedium,
    color: StitchColors.onSurfaceVariant,
  },
  hubLevelGridCellEmpty: {
    fontSize: 12,
    fontFamily: StitchFonts.body,
    color: StitchColors.onSurfaceVariant,
    lineHeight: 17,
  },
  hubSmallMetaText: {
    fontSize: 13,
    fontFamily: StitchFonts.bodySemi,
    color: StitchColors.onSurfaceVariant,
  },
  hubAchievement: {
    padding: 32,
    borderRadius: StitchRadius.lg,
    borderWidth: 1,
    borderColor: `${StitchColors.primary}14`,
    backgroundColor: `${StitchColors.primary}0C`,
    flexDirection: "column",
    gap: 16,
  },
  hubAchievementTitle: {
    fontSize: 22,
    fontFamily: StitchFonts.headline,
    color: StitchColors.onSurface,
    marginBottom: 4,
  },
  hubAchievementDesc: {
    fontSize: 15,
    fontFamily: StitchFonts.bodyMedium,
    color: StitchColors.onSurfaceVariant,
  },
});
