import { StyleSheet } from "react-native";

import {
  StitchColors,
  StitchFonts,
  StitchRadius,
} from "@/src/theme/wordlyStitchTheme";

export const revisionFiltersSheetStyles = StyleSheet.create({
  modalRoot: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "transparent",
  },
  scrim: {
    backgroundColor: "rgba(47, 51, 52, 0.4)",
  },
  sheet: {
    width: "100%",
    backgroundColor: StitchColors.surfaceContainerLowest,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    maxHeight: "88%",
    overflow: "hidden",
    shadowColor: StitchColors.onSurface,
    shadowOpacity: 0.12,
    shadowRadius: 40,
    shadowOffset: { width: 0, height: -8 },
    elevation: 24,
  },
  handle: {
    width: 48,
    height: 5,
    borderRadius: 3,
    backgroundColor: StitchColors.surfaceContainerHighest,
    alignSelf: "center",
    marginTop: 10,
    marginBottom: 6,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 14,
  },
  headerBtnText: {
    fontSize: 15,
    fontFamily: StitchFonts.headline,
    color: StitchColors.primary,
    fontWeight: "600",
  },
  headerTitle: {
    flex: 1,
    textAlign: "center",
    fontSize: 17,
    fontFamily: StitchFonts.headline,
    color: StitchColors.onSurface,
    letterSpacing: -0.3,
  },
  closeBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: StitchColors.surfaceContainerLow,
    alignItems: "center",
    justifyContent: "center",
  },
  scroll: {
    maxHeight: 440,
    paddingHorizontal: 22,
    paddingBottom: 8,
  },
  section: {
    marginBottom: 22,
  },
  sectionLabel: {
    fontSize: 11,
    fontFamily: StitchFonts.headline,
    fontWeight: "700",
    color: StitchColors.onSurfaceVariant,
    letterSpacing: 1.2,
    textTransform: "uppercase",
    marginBottom: 12,
  },
  chipWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  levelChip: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: StitchRadius.md,
    backgroundColor: StitchColors.surfaceContainerLow,
  },
  levelChipOn: {
    backgroundColor: StitchColors.primary,
    shadowColor: StitchColors.primary,
    shadowOpacity: 0.22,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  levelChipText: {
    fontSize: 14,
    fontFamily: StitchFonts.bodySemi,
    color: StitchColors.onSurfaceVariant,
  },
  levelChipTextOn: {
    color: StitchColors.onPrimary,
  },
  dateSegmentOuter: {
    width: "100%",
  },
  dateSegmentTrack: {
    padding: 4,
    borderRadius: StitchRadius.lg,
    backgroundColor: StitchColors.surfaceContainerLow,
    overflow: "hidden",
  },
  dateSegmentInner: {
    position: "relative",
    flexDirection: "row",
    minHeight: 46,
  },
  dateSegmentThumb: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    borderRadius: StitchRadius.md,
    backgroundColor: StitchColors.primary,
    shadowColor: StitchColors.primary,
    shadowOpacity: 0.22,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  dateSegmentLabelsRow: {
    flexDirection: "row",
    position: "relative",
    zIndex: 1,
    minHeight: 46,
    width: "100%",
  },
  dateSegmentHalf: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: 8,
  },
  dateSegmentLabel: {
    fontSize: 14,
    fontFamily: StitchFonts.bodySemi,
    color: StitchColors.onSurfaceVariant,
  },
  dateSegmentLabelOn: {
    color: StitchColors.onPrimary,
  },
  sortLevelGrid: {
    flexDirection: "row",
    gap: 12,
  },
  sortLevelCell: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 16,
    paddingHorizontal: 10,
    borderRadius: StitchRadius.lg,
    backgroundColor: StitchColors.surfaceContainerLow,
  },
  sortLevelCellOn: {
    backgroundColor: StitchColors.surfaceContainer,
  },
  sortLevelCellText: {
    fontSize: 13,
    fontFamily: StitchFonts.bodySemi,
    color: StitchColors.onSurface,
    textAlign: "center",
    flexShrink: 1,
  },
  sortLevelCellTextOn: {
    color: StitchColors.primary,
  },
  footer: {
    paddingHorizontal: 22,
    paddingTop: 12,
    paddingBottom: 8,
    backgroundColor: StitchColors.surfaceContainerLowest,
  },
  applyBtn: {
    backgroundColor: StitchColors.primary,
    borderRadius: StitchRadius.full,
    paddingVertical: 16,
    alignItems: "center",
    shadowColor: StitchColors.primary,
    shadowOpacity: 0.35,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  applyBtnText: {
    fontSize: 17,
    fontFamily: StitchFonts.headline,
    color: StitchColors.onPrimary,
    fontWeight: "700",
  },
});
